exclude: tests

repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-bugbear,
          flake8-annotations,
          flake8-comprehensions,
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - maxminddb
          - tqdm
          - netaddr
          - tqdm-stubs
          - types-requests
          - parfive
          - typer
          - git+https://github.com/VimT/MaxMind-DB-Writer-python
        args:
          - --strict
          - --implicit-reexport
          - --install-types
          - --config-file
          - pyproject.toml
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: ["--in-place", "--pre-summary-newline"]
  - repo: https://github.com/PyCQA/doc8
    rev: v1.0.0
    hooks:
     - id: doc8
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
